"""Supplementary material for the Pattern Recognition Letters version, from the released result files.

    python paper/prl/make_supplement_prl.py        # run from the repository root

Writes paper/prl/supplementary_prl.md and, if pandoc is available, supplementary_prl.docx and .pdf.
Table numbers S1-S9 and Figs. S1-S2 are the ones cited in the manuscript.
"""
import json
import re
import shutil
import subprocess
from pathlib import Path

import numpy as np
import pandas as pd
from scipy import stats

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
R = ROOT / 'results'
C = ['none', 'lfa', 'se', 'cbam']
L = {'none': 'None', 'lfa': 'LFA', 'se': 'SE', 'cbam': 'CBAM'}
CL = {'Algal': 'Algal leaf spot', 'Leaf_rot': 'Leaf rot', 'Phomopsis': '*Phomopsis* leaf spot',
      'Root_disease': 'Root and collar rot'}

TRAINING_SETTINGS = [
    ('Backbone', 'EfficientNet-B0, torchvision ImageNet weights (IMAGENET1K_V1)'),
    ('Input', 'Train: RandomResizedCrop(224, scale 0.7–1.0). Evaluation: Resize(256) on the short side, CenterCrop(224)'),
    ('Augmentation', 'Horizontal flip p = 0.5; vertical flip p = 0.3; RandomAffine (rotation ±20°, translation 5 %, scale 0.95–1.05); '
                     'ColorJitter (brightness 0.3, contrast 0.3, saturation 0.2, hue 0.05); GaussianBlur (kernel 3–7, σ 0.1–1.5); '
                     'ImageNet normalisation; RandomErasing p = 0.3, 2–10 % of the image'),
    ('Classifier head', 'Dropout p = 0.3, Linear(1280, 4)'),
    ('Stage 1', '15 epochs, backbone frozen (BatchNorm statistics still updating), Adam, lr 1e-3, attention module + head trained'),
    ('Stage 2', '15 epochs, all parameters trainable, Adam, lr 1e-5, starting from the best stage-1 checkpoint'),
    ('Checkpoint selection', 'Highest inner-validation macro F1 over both stages; inner validation ≈ 10 % of the training part, by whole groups'),
    ('Loss and sampling', 'Cross-entropy with inverse-frequency class weights; WeightedRandomSampler with class weights'),
    ('Batch size', '16'),
    ('Precision', 'Mixed precision (torch.autocast with a gradient scaler)'),
    ('Seeds', '0 and 1 per fold; Python, NumPy, PyTorch, sampler and data-loader workers seeded; cuDNN deterministic'),
    ('Hardware', 'Google Colab GPU runtime; PyTorch and torchvision'),
]


def ttest_block(d, ntr, nte):
    d = np.asarray(d, float)
    J = len(d)
    se = np.sqrt((1 / J + nte / ntr) * d.var(ddof=1))
    h = stats.t.ppf(0.975, J - 1) * se
    return d.mean(), d.mean() - h, d.mean() + h, 2 * stats.t.sf(abs(d.mean() / se), J - 1)


def main():
    d = json.load(open(R / 'numbers.json'))
    runs = pd.read_csv(R / 'run_metrics.csv')
    res = pd.read_csv(R / 'results.csv')
    sz = res.groupby(['repeat', 'fold'])[['n_train', 'n_val', 'n_test']].first()
    ntr, nte = (sz.n_train + sz.n_val).mean(), sz.n_test.mean()
    out = ['---', 'title: "Supplementary material"',
           'subtitle: "Seed-to-seed variation outweighs lightweight attention gains: a grouped, repeated cross-validation study on field durian disease images"',
           'author: "Lin Ding Shan (UCSI University)"',
           'header-includes: \\renewcommand{\\thefigure}{S\\arabic{figure}}', '---', '',
           'All tables and figures are generated by `paper/prl/make_supplement_prl.py` from the released result files '
           '(`results/preds.csv`, `results/results.csv`, `results/v2/results.csv` and the derived `numbers.json`).', '']

    # S1 per-class
    out += ['## Table S1. Per-class precision, recall and F1 (%, mean ± SD over runs in which the class was present), all test images', '',
            '| Class | Configuration | Precision | Recall | F1 |', '|---|---|---|---|---|']
    for cl in CL:
        for i, c in enumerate(C):
            v = d['per_class'][f'{c}|{cl}']
            out.append(f"| {CL[cl] if i == 0 else ''} | {L[c]} | {v['precision']} | {v['recall']} | {v['f1']} |")

    # S2 accuracy
    out += ['', '## Table S2. Accuracy (%, mean ± SD over 40 runs) and paired difference from the plain network over 20 folds (corrected resampled *t*-test)', '',
            '| Configuration | Accuracy | Difference (pp) [95% CI] | *p*, corrected | Folds higher |', '|---|---|---|---|---|']
    for c in C:
        s = d['summary'][c]
        if c == 'none':
            out.append(f"| {L[c]} | {s['acc_mean']:.2f} ± {s['acc_sd']:.2f} | – | – | – |")
        else:
            p = d['paired_accuracy'][c]
            out.append(f"| {L[c]} | {s['acc_mean']:.2f} ± {s['acc_sd']:.2f} | {p['mean']:+.2f} [{p['ci_low']:.2f}, {p['ci_high']:.2f}] | {p['p_corrected']:.3f} | {int(p['wins'])}/20 |")

    # S3 preliminary
    a = pd.read_csv(R / 'ablation_replicates_preliminary.csv')
    y = a[a.attention == 'none'].macro_f1
    out += ['', '## Table S3. Preliminary experiment: eight runs per configuration on one fixed five-class split (earlier code; training randomness not controlled by the seed, so replicates are unpaired)', '',
            '| Configuration | Macro F1, mean ± SD | Difference from none (pp) | *p*, Welch *t* | *p*, Mann–Whitney |', '|---|---|---|---|---|']
    for c in C:
        x = a[a.attention == c].macro_f1
        if c == 'none':
            out.append(f'| {L[c]} | {x.mean():.2f} ± {x.std(ddof=1):.2f} | – | – | – |')
        else:
            out.append(f"| {L[c]} | {x.mean():.2f} ± {x.std(ddof=1):.2f} | {x.mean() - y.mean():+.2f} | "
                       f"{stats.ttest_ind(x, y, equal_var=False).pvalue:.3f} | {stats.mannwhitneyu(x, y).pvalue:.3f} |")

    # S4 four-class metric
    pf0 = res.groupby(['repeat', 'fold', 'config']).test_macro_f1.mean().unstack('config')[C]
    out += ['', '## Table S4. Macro F1 averaged over all four classes (an absent class scored as zero), as stored by the training notebooks and used in the pre-specified decision rule', '',
            '| Configuration | Macro F1 (%), mean ± SD | Paired difference (pp) [95% CI] | *p*, corrected | Meets rule (≥ 2 pp and CI > 0) |', '|---|---|---|---|---|']
    for c in C:
        v = res[res.config == c].test_macro_f1
        if c == 'none':
            out.append(f'| {L[c]} | {v.mean():.2f} ± {v.std(ddof=1):.2f} | – | – | – |')
        else:
            m, lo, hi, p = ttest_block(pf0[c] - pf0['none'], ntr, nte)
            out.append(f'| {L[c]} | {v.mean():.2f} ± {v.std(ddof=1):.2f} | {m:+.2f} [{lo:.2f}, {hi:.2f}] | {p:.3f} | {"yes" if (m >= 2 and lo > 0) else "no"} |')

    # S5 training settings
    out += ['', '## Table S5. Training settings (identical for all configurations)', '', '| Item | Setting |', '|---|---|']
    out += [f'| {k} | {v} |' for k, v in TRAINING_SETTINGS]

    # S6 other tests
    out += ['', '## Table S6. Paired comparisons of macro F1 with the plain network under three tests over the 20 folds', '',
            '| Configuration | Mean difference (pp) | *p*, corrected resampled *t* | *p*, uncorrected paired *t* | *p*, Wilcoxon signed-rank |', '|---|---|---|---|---|']
    for c in C[1:]:
        p = d['paired_macro_f1'][c]
        out.append(f"| {L[c]} | {p['mean']:+.2f} | {p['p_corrected']:.3f} | {p['p_uncorrected']:.3f} | {p['p_wilcoxon']:.3f} |")

    # S7 grouping sensitivity
    sg = pd.read_csv(R / 'sensitivity_grouping.csv')
    VN = {'all': 'All test images', 'no_video': 'Video frames excluded',
          'unsplit_linked': 'Only images whose video-linked group was not split'}
    out += ['', '## Table S7. Sensitivity to the grouping of video frames (Section 2.1 of the manuscript)', '',
            '| Test images scored | Mean test images per fold | Configuration | Macro F1 (%), mean ± SD | Paired difference (pp) [95% CI] | *p*, corrected |',
            '|---|---|---|---|---|---|']
    for v in VN:
        for i, c in enumerate(C):
            r = sg[(sg.variant == v) & (sg.config == c)].iloc[0]
            lead = f'| {VN[v]} | {r.test_n_mean:.1f} ' if i == 0 else '| | '
            diff = '– | –' if c == 'none' else f'{r["mean"]:+.2f} [{r.ci_low:.2f}, {r.ci_high:.2f}] | {r.p_corrected:.3f}'
            out.append(f'{lead}| {L[c]} | {r.macro_f1_mean:.2f} ± {r.macro_f1_sd:.2f} | {diff} |')
    g = d['grouping']
    out += ['', f"Without the video frames the mean seed difference was {g['no_video_seed_gap_mean']:.2f} points, and LFA was at least 3 points ahead of the plain "
            f"network in {g['no_video_lfa_share_ahead_3pp'] * 100:.1f} % of seed-matched pairs and at least 3 points behind in {g['no_video_lfa_share_behind_3pp'] * 100:.1f} %."]

    # S8 cost
    lat = pd.read_csv(R / 'latency_params.csv')
    out += ['', '## Table S8. Model size, computation and CPU latency for one 224 × 224 image (median and 90th percentile of 200 passes, Colab CPU)', '',
            '| Configuration | Parameters (M) | Added parameters | GMACs | 1 thread, median (ms) | 1 thread, p90 (ms) | 12 threads, median (ms) | 12 threads, p90 (ms) |',
            '|---|---|---|---|---|---|---|---|']
    for _, r in lat.set_index('config').loc[C].reset_index().iterrows():
        out.append(f"| {L[r.config]} | {r.params_M:.4f} | {int(r.extra_params):,} | {r.GMACs:.4f} | {r.cpu_ms_1thr_median:.2f} | {r.cpu_ms_1thr_p90:.2f} | {r.cpu_ms_12thr_median:.2f} | {r.cpu_ms_12thr_p90:.2f} |")

    # S9 per fold
    pf = runs.groupby(['repeat', 'fold', 'config']).macro_f1.mean().unstack('config')[C]
    cls = runs.groupby(['repeat', 'fold']).classes_in_test.first()
    out += ['', '## Table S9. Fold sizes and macro F1 per fold (%, mean of two seeds; † no root and collar rot image in the test fold)', '',
            '| Repeat | Fold | Train | Validation | Test | None | LFA | SE | CBAM |', '|---|---|---|---|---|---|---|---|---|']
    for (rep, k), row in pf.iterrows():
        s = sz.loc[(rep, k)]
        out.append(f"| {rep} | {k}{'†' if cls[(rep, k)] < 4 else ''} | {s.n_train} | {s.n_val} | {s.n_test} | "
                   + ' | '.join(f'{row[c]:.2f}' for c in C) + ' |')

    # figures
    for f in ['fig5_confusion.png', 'fig4_fold_spread.png']:
        shutil.copy(ROOT / 'figures' / f, HERE / 'figs' / f)
    out += ['', '## Figures S1 and S2', '', '![Confusion matrices of the plain network and LFA, pooled over the 40 runs of each configuration and normalised by row (%).](figs/fig5_confusion.png){ width=100% }', '',
            '![Macro F1 of each configuration on each of the 20 folds (grey lines, mean of two seeds) and the mean over folds (blue).](figs/fig4_fold_spread.png){ width=70% }', '']

    text = re.sub(r'(?<=[\s\[(,|])-(?=\d)', '−', '\n'.join(out))
    md = HERE / 'supplementary_prl.md'
    md.write_text(text)
    print('wrote', md)
    if shutil.which('pandoc'):
        subprocess.run(['pandoc', str(md), '-o', str(HERE / 'supplementary_prl.docx'), '--resource-path', str(HERE)], check=True)
        subprocess.run(['pandoc', str(md), '-o', str(HERE / 'supplementary_prl.pdf'), '--resource-path', str(HERE),
                        '--pdf-engine=xelatex', '-V', 'geometry:margin=2cm', '-V', 'mainfont=DejaVu Serif', '-V', 'fontsize=9pt'], check=True)
        print('wrote docx and pdf')


if __name__ == '__main__':
    main()
