"""Supplementary material of the paper, from the released result files.

    python paper/make_supplement.py      # run from the repository root, after analyze.py and paper/compute_numbers.py

Writes paper/supplementary.md and, if pandoc is available, supplementary.docx (and .pdf if a LaTeX engine works).
Table numbers S1-S10 and Figs. S1-S2 are the ones cited in the manuscript. The single-channel spatial gate (SG)
is called lfa in the code and result files.
"""
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path

import numpy as np
import pandas as pd
from scipy import stats

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
R = ROOT / 'results'
C = ['none', 'lfa', 'se', 'cbam']
L = {'none': 'None', 'lfa': 'SG', 'se': 'SE', 'cbam': 'CBAM'}
CL = {'Algal': 'Algal leaf spot', 'Leaf_rot': 'Leaf blight complex', 'Phomopsis': '*Phomopsis* leaf spot',
      'Root_disease': 'Root and collar rot'}

TRAINING_SETTINGS = [
    ('Backbone', 'EfficientNet-B0, torchvision ImageNet weights (IMAGENET1K_V1)'),
    ('Input', 'Train: RandomResizedCrop(224, scale 0.7–1.0). Evaluation: Resize(256) on the short side, CenterCrop(224)'),
    ('Augmentation', 'Horizontal flip p = 0.5; vertical flip p = 0.3; RandomAffine (rotation ±20°, translation 5 %, scale 0.95–1.05); '
                     'ColorJitter (brightness 0.3, contrast 0.3, saturation 0.2, hue 0.05); GaussianBlur (kernel 3–7, σ 0.1–1.5); '
                     'ImageNet normalisation; RandomErasing p = 0.3, 2–10 % of the image'),
    ('Classifier head', 'Dropout p = 0.3, Linear(1280, 4)'),
    ('Stage 1', '15 epochs, backbone frozen (BatchNorm statistics still updating), Adam, lr 1e-3, attention module + head trained'),
    ('Stage 2', '15 epochs, all parameters trainable, Adam, lr 1e-5, starting from the best stage-1 checkpoint'),
    ('Checkpoint selection', 'Highest inner-validation macro F1 over both stages; inner validation ≈ 10 % of the training part, by whole groups'),
    ('Loss and sampling', 'Cross-entropy with inverse-frequency class weights; WeightedRandomSampler with class weights'),
    ('Batch size', '16'),
    ('Precision', 'Mixed precision (torch.autocast with a gradient scaler)'),
    ('Seeds', '0 and 1 per fold; Python, NumPy, PyTorch, sampler and data-loader workers seeded; cuDNN deterministic'),
    ('Hardware', 'Google Colab GPU runtime; PyTorch and torchvision'),
]


def pf4(x):
    return '< 0.0001' if x < 0.0001 else f'{x:.4f}'


def sep(*w):
    """Pipe-table separator whose dash counts set the relative column widths in pandoc."""
    return '|' + '|'.join('-' * x for x in w) + '|'


def ttest_block(d, ntr, nte):
    d = np.asarray(d, float)
    J = len(d)
    se = np.sqrt((1 / J + nte / ntr) * d.var(ddof=1))
    h = stats.t.ppf(0.975, J - 1) * se
    return d.mean(), d.mean() - h, d.mean() + h, 2 * stats.t.sf(abs(d.mean() / se), J - 1)


TITLE = 'Decision support for durian disease diagnosis from field photographs: grouped validation, backbone choice and referral to the grower'
BLIND = '--blind' in sys.argv      # anonymised copy for double-anonymised review
STEM = 'supplementary_blind' if BLIND else 'supplementary'


def main():
    d = json.load(open(R / 'numbers.json'))
    runs = pd.read_csv(R / 'run_metrics.csv')
    res = pd.read_csv(R / 'results.csv')
    sz = res.groupby(['repeat', 'fold'])[['n_train', 'n_val', 'n_test']].first()
    ntr, nte = (sz.n_train + sz.n_val).mean(), sz.n_test.mean()
    out = ['---', 'title: "Supplementary material"',
           f'subtitle: "{TITLE}"',
           *([] if BLIND else ['author: "Lin Ding Shan (Independent researcher, Malaysia)"']),
           'header-includes: \\renewcommand{\\thefigure}{S\\arabic{figure}}', '---', '',
           'All tables and figures are generated by `paper/make_supplement.py` from the released result files '
           '(`results/preds.csv`, `results/results.csv`, `results/v2/results.csv`, `results/v3/*`, `results/numbers.json`, `paper/numbers.json` and `paper/numbers_v3.json`). '
           'The single-channel spatial gate (SG) is labelled `lfa` / LFA in the code, the result files and Figs. S1–S2, '
           'and the leaf blight complex is labelled `Leaf_rot`.', '']

    # S1 per-class
    out += ['## Table S1. Per-class precision, recall and F1 (%, mean ± SD over runs in which the class was present), all test images', '',
            '| Class | Configuration | Precision | Recall | F1 |', '|---|---|---|---|---|']
    for cl in CL:
        for i, c in enumerate(C):
            v = d['per_class'][f'{c}|{cl}']
            out.append(f"| {CL[cl] if i == 0 else ''} | {L[c]} | {v['precision']} | {v['recall']} | {v['f1']} |")

    # S2 accuracy
    out += ['', '## Table S2. Accuracy (%, mean ± SD over 40 runs) and paired difference from the plain network over 20 folds (corrected resampled *t*-test)', '',
            '| Configuration | Accuracy | Difference (pp) [95% CI] | *p*, corrected | Folds higher |', '|---|---|---|---|---|']
    for c in C:
        s = d['summary'][c]
        if c == 'none':
            out.append(f"| {L[c]} | {s['acc_mean']:.2f} ± {s['acc_sd']:.2f} | – | – | – |")
        else:
            p = d['paired_accuracy'][c]
            out.append(f"| {L[c]} | {s['acc_mean']:.2f} ± {s['acc_sd']:.2f} | {p['mean']:+.2f} [{p['ci_low']:.2f}, {p['ci_high']:.2f}] | {p['p_corrected']:.3f} | {int(p['wins'])}/20 |")

    # S3 preliminary
    a = pd.read_csv(R / 'ablation_replicates_preliminary.csv')
    y = a[a.attention == 'none'].macro_f1
    out += ['', '## Table S3. Preliminary experiment: eight runs per configuration on one fixed five-class split (earlier code; training randomness not controlled by the seed, so replicates are unpaired)', '',
            '| Configuration | Macro F1, mean ± SD | Difference from none (pp) | *p*, Welch *t* | *p*, Mann–Whitney |', '|---|---|---|---|---|']
    for c in C:
        x = a[a.attention == c].macro_f1
        if c == 'none':
            out.append(f'| {L[c]} | {x.mean():.2f} ± {x.std(ddof=1):.2f} | – | – | – |')
        else:
            out.append(f"| {L[c]} | {x.mean():.2f} ± {x.std(ddof=1):.2f} | {x.mean() - y.mean():+.2f} | "
                       f"{stats.ttest_ind(x, y, equal_var=False).pvalue:.3f} | {stats.mannwhitneyu(x, y).pvalue:.3f} |")

    # S4 four-class metric
    pf0 = res.groupby(['repeat', 'fold', 'config']).test_macro_f1.mean().unstack('config')[C]
    out += ['', '## Table S4. Macro F1 averaged over all four classes (an absent class scored as zero), as stored by the training notebooks and used in the pre-specified decision rule', '',
            '| Configuration | Macro F1 (%), mean ± SD | Paired difference (pp) [95% CI] | *p*, corrected | Meets rule (≥ 2 pp and CI > 0) |', '|---|---|---|---|---|']
    for c in C:
        v = res[res.config == c].test_macro_f1
        if c == 'none':
            out.append(f'| {L[c]} | {v.mean():.2f} ± {v.std(ddof=1):.2f} | – | – | – |')
        else:
            m, lo, hi, p = ttest_block(pf0[c] - pf0['none'], ntr, nte)
            out.append(f'| {L[c]} | {v.mean():.2f} ± {v.std(ddof=1):.2f} | {m:+.2f} [{lo:.2f}, {hi:.2f}] | {p:.3f} | {"yes" if (m >= 2 and lo > 0) else "no"} |')

    # S5 training settings
    out += ['', '## Table S5. Training settings (identical for all configurations)', '', '| Item | Setting |', '|---|---|']
    out += [f'| {k} | {v} |' for k, v in TRAINING_SETTINGS]

    # S6 other tests
    out += ['', '## Table S6. Paired comparisons of macro F1 with the plain network under three tests over the 20 folds', '',
            '| Configuration | Mean difference (pp) | *p*, corrected resampled *t* | *p*, uncorrected paired *t* | *p*, Wilcoxon signed-rank |', '|---|---|---|---|---|']
    for c in C[1:]:
        p = d['paired_macro_f1'][c]
        out.append(f"| {L[c]} | {p['mean']:+.2f} | {p['p_corrected']:.3f} | {p['p_uncorrected']:.3f} | {p['p_wilcoxon']:.3f} |")

    # S7 grouping sensitivity
    sg = pd.read_csv(R / 'sensitivity_grouping.csv')
    VN = {'all': 'All test images', 'no_video': 'Video frames excluded',
          'unsplit_linked': 'Only images whose video-linked group was not split'}
    out += ['', '## Table S7. Sensitivity to the grouping of video frames (Section 2.3 of the manuscript)', '',
            '| Test images scored | Mean test images per fold | Configuration | Macro F1 (%), mean ± SD | Paired difference (pp) [95% CI] | *p*, corrected |',
            '|---|---|---|---|---|---|']
    for v in VN:
        for i, c in enumerate(C):
            r = sg[(sg.variant == v) & (sg.config == c)].iloc[0]
            lead = f'| {VN[v]} | {r.test_n_mean:.1f} ' if i == 0 else '| | '
            diff = '– | –' if c == 'none' else f'{r["mean"]:+.2f} [{r.ci_low:.2f}, {r.ci_high:.2f}] | {r.p_corrected:.3f}'
            out.append(f'{lead}| {L[c]} | {r.macro_f1_mean:.2f} ± {r.macro_f1_sd:.2f} | {diff} |')
    g = d['grouping']
    out += ['', f"Without the video frames the mean seed difference was {g['no_video_seed_gap_mean']:.2f} points, and the SG was at least 3 points ahead of the plain "
            f"network in {g['no_video_lfa_share_ahead_3pp'] * 100:.1f} % of seed-matched pairs and at least 3 points behind in {g['no_video_lfa_share_behind_3pp'] * 100:.1f} %."]

    # S8 cost
    lat = pd.read_csv(R / 'latency_params.csv')
    out += ['', '## Table S8. Model size, computation and CPU latency for one 224 × 224 image (median and 90th percentile of 200 passes, Colab CPU)', '',
            '| Configuration | Parameters (M) | Added parameters | GMACs | 1 thread, median (ms) | 1 thread, p90 (ms) | 12 threads, median (ms) | 12 threads, p90 (ms) |',
            '|---|---|---|---|---|---|---|---|']
    for _, r in lat.set_index('config').loc[C].reset_index().iterrows():
        out.append(f"| {L[r.config]} | {r.params_M:.4f} | {int(r.extra_params):,} | {r.GMACs:.4f} | {r.cpu_ms_1thr_median:.2f} | {r.cpu_ms_1thr_p90:.2f} | {r.cpu_ms_12thr_median:.2f} | {r.cpu_ms_12thr_p90:.2f} |")

    # S9 per fold
    pf = runs.groupby(['repeat', 'fold', 'config']).macro_f1.mean().unstack('config')[C]
    cls = runs.groupby(['repeat', 'fold']).classes_in_test.first()
    out += ['', '## Table S9. Fold sizes and macro F1 per fold (%, mean of two seeds; † no root and collar rot image in the test fold)', '',
            '| Repeat | Fold | Train | Validation | Test | None | SG | SE | CBAM |', '|---|---|---|---|---|---|---|---|---|']
    for (rep, k), row in pf.iterrows():
        s = sz.loc[(rep, k)]
        out.append(f"| {rep} | {k}{'†' if cls[(rep, k)] < 4 else ''} | {s.n_train} | {s.n_val} | {s.n_test} | "
                   + ' | '.join(f'{row[c]:.2f}' for c in C) + ' |')

    # figures
    for f in ['fig5_confusion.png', 'fig4_fold_spread.png']:
        shutil.copy(ROOT / 'figures' / f, HERE / 'figures' / f)
    out += ['', '## Figures S1 and S2', '', '![Confusion matrices of the plain network and the SG (labelled LFA), pooled over the 40 runs of each configuration and normalised by row (%), all test images.](figures/fig5_confusion.png){ width=100% }', '',
            '![Macro F1 of each configuration on each of the 20 folds (grey lines, mean of two seeds) and the mean over folds (blue), all test images.](figures/fig4_fold_spread.png){ width=70% }', '']

    # S10 per-class, video frames excluded (primary scoring)
    P = json.load(open(HERE / 'numbers.json'))['main_novid']['per_class']
    out += ['## Table S10. Per-class precision, recall and F1 (%, mean ± SD over runs in which the class was present), video frames excluded (primary scoring)', '',
            '| Class | Configuration | Precision | Recall | F1 | Runs |', '|---|---|---|---|---|---|']
    for cl in CL:
        for i, c in enumerate(C):
            v = P[c][cl]
            out.append(f"| {CL[cl] if i == 0 else ''} | {L[c]} | {v['p'][0]:.1f} ± {v['p'][1]:.1f} | {v['r'][0]:.1f} ± {v['r'][1]:.1f} | {v['f1'][0]:.1f} ± {v['f1'][1]:.1f} | {v['runs']} |")
    out.append('')

    # ---- backbone and decision-support experiment (results/v3) ----
    V = json.load(open(HERE / 'numbers_v3.json'))
    BB = ['effb0', 'mnv3l', 'mnv4m', 'cnxv2t', 'vits']
    BL = {'effb0': 'EfficientNet-B0', 'mnv3l': 'MobileNetV3-Large', 'mnv4m': 'MobileNetV4-Conv-Medium',
          'cnxv2t': 'ConvNeXt V2-Tiny', 'vits': 'ViT-S/16'}
    SC = {'novid': 'video frames excluded (primary)', 'all': 'all test images'}
    out += ['## Table S11. Backbone comparison: macro F1 and accuracy (%, mean ± SD over 40 runs) and paired difference from EfficientNet-B0 over 20 folds', '',
            'Corrected resampled *t*-test (factor %.3f); Holm adjustment over the four comparisons; "rule" is the pre-specified criterion (difference of at least 2 pp and Holm *p* < 0.05).' % V['factor'], '',
            '| Scoring | Backbone | Macro F1 | Accuracy | Difference (pp) [95% CI] | *p*, corrected | *p*, Holm | *p*, uncorrected *t* | *p*, Wilcoxon | Folds higher | Rule met | Mean seed difference (pp) |',
            sep(14, 22, 14, 8, 24, 8, 8, 9, 9, 7, 6, 9)]
    for sc in ['novid', 'all']:
        b = V[sc]
        for i, c in enumerate(BB):
            sm = b['summary'][c]
            lead = f'| {SC[sc]} ' if i == 0 else '| '
            if c == 'effb0':
                out.append(f"{lead}| {BL[c]} | {sm['mean']:.2f} ± {sm['sd']:.2f} | {sm['acc_mean']:.2f} | – | – | – | – | – | – | – | {b['seed_abs_by_config'][c]:.2f} |")
            else:
                p = b['paired'][c]
                out.append(f"{lead}| {BL[c]} | {sm['mean']:.2f} ± {sm['sd']:.2f} | {sm['acc_mean']:.2f} | {p['mean']:+.2f} [{p['ci_low']:.2f}, {p['ci_high']:.2f}] | "
                           f"{p['p_corrected']:.3f} | {p['p_holm']:.3f} | {pf4(p['p_uncorrected'])} | {pf4(p['p_wilcoxon'])} | {p['wins']}/20 | {'yes' if p['improvement_rule'] else 'no'} | {b['seed_abs_by_config'][c]:.2f} |")
    cv = V['novid']['cnxv2t_vs_vits']
    out += ['', f"ConvNeXt V2-Tiny minus ViT-S/16 (exploratory, video frames excluded): {cv['mean']:+.2f} pp [{cv['ci_low']:.2f}, {cv['ci_high']:.2f}], corrected *p* = {cv['p_corrected']:.3f}.", '']

    out += ['## Table S12. Per-class precision, recall and F1 (%, mean ± SD over runs in which the class was present), backbone experiment, video frames excluded', '',
            '| Class | Backbone | Precision | Recall | F1 | Runs |', sep(18, 26, 14, 14, 14, 6)]
    for cl in CL:
        for i, c in enumerate(BB):
            v = V['novid']['per_class'][c][cl]
            out.append(f"| {CL[cl] if i == 0 else ''} | {BL[c]} | {v['p'][0]:.1f} ± {v['p'][1]:.1f} | {v['r'][0]:.1f} ± {v['r'][1]:.1f} | {v['f1'][0]:.1f} ± {v['f1'][1]:.1f} | {v['runs']} |")
    out += ['', '## Table S13. Recall (%) for *Phomopsis* leaf spot, still photographs against video frames, pooled over the 40 runs of each backbone (all test images)', '',
            '| Backbone | Still photographs | Video frames |', sep(24, 14, 14)]
    for c in BB:
        r = V['all']['phomopsis_recall'][c]
        out.append(f"| {BL[c]} | {r['stills']:.1f} | {r['video']:.1f} |")

    out += ['', '## Table S14. Referral to the grower: the threshold on the maximum softmax probability is chosen on the inner-validation images only (smallest threshold at which the accepted validation images reach the target accuracy; all images are referred if none does)', '',
            '*Coverage*: share of test images decided by the model. *Accuracy decided*: mean over runs with at least one decided image (pooled over images in brackets). *Accuracy, no referral*: accuracy if every image were decided (pooled). *Below target*: runs in which the accuracy on decided images was below the target. *All decided*: runs in which every test image was decided. Referral shares are means over runs in which the class was present.', '',
            '| Scoring | Target | Backbone | Coverage (%) | Accuracy decided (%) | Accuracy, no referral (%) | Below target | All decided | Referred: Algal | Referred: Leaf blight | Referred: *Phomopsis* | Referred: Root rot |',
            sep(13, 7, 22, 13, 17, 10, 8, 8, 8, 8, 9, 8)]
    for sc in ['novid', 'all']:
        for tg in ['90', '95']:
            for i, c in enumerate(BB):
                x = V[sc]['selective'][tg][c]
                dp = x['defer_pct_run_mean']
                lead = f'| {SC[sc]} | {tg} % ' if i == 0 else '| | '
                out.append(f"{lead}| {BL[c]} | {x['coverage'][0]:.1f} ± {x['coverage'][1]:.1f} | {x['sel_acc_mean_of_runs'][0]:.1f} ± {x['sel_acc_mean_of_runs'][1]:.1f} ({x['sel_acc_pooled']:.1f}) | "
                           f"{x['acc_all_pooled']:.1f} | {x['runs_below_target']}/{x['runs_with_accepted']} | {x['runs_all_accepted']}/40 | "
                           f"{dp['Algal']:.1f} | {dp['Leaf_rot']:.1f} | {dp['Phomopsis']:.1f} | {dp['Root_disease']:.1f} |")

    out += ['', '## Table S15. Threshold-free confidence ranking: accuracy on the most confident images at fixed coverage, area under the risk–coverage curve (AURC, lower is better) and top-2 accuracy (%, mean over 40 runs; video frames excluded)', '',
            '| Backbone | 50 % coverage | 70 % coverage | 80 % coverage | 100 % (accuracy) | AURC (mean ± SD) | Top-2 accuracy (mean ± SD) |', sep(22, 11, 11, 11, 11, 15, 15)]
    for c in BB:
        a = V['novid']['aurc_top2'][c]
        out.append(f"| {BL[c]} | {a['acc_at_50']:.1f} | {a['acc_at_70']:.1f} | {a['acc_at_80']:.1f} | {a['acc_at_100']:.1f} | {a['aurc'][0]:.2f} ± {a['aurc'][1]:.2f} | {a['top2'][0]:.2f} ± {a['top2'][1]:.2f} |")
    out += ['', 'Exploratory paired comparisons with EfficientNet-B0 over 20 folds (corrected resampled *t*-test, Holm over four comparisons; no test of these quantities was pre-specified):', '',
            '| Backbone | AURC difference [95% CI] | *p* | *p*, Holm | Top-2 difference (pp) [95% CI] | *p* | *p*, Holm |', sep(22, 20, 7, 8, 20, 7, 8)]
    for c in BB[1:]:
        a, t = V['novid']['aurc_paired'][c], V['novid']['top2_paired'][c]
        out.append(f"| {BL[c]} | {a['mean']:+.2f} [{a['ci_low']:.2f}, {a['ci_high']:.2f}] | {a['p_corrected']:.3f} | {a['p_holm']:.3f} | "
                   f"{t['mean']:+.2f} [{t['ci_low']:.2f}, {t['ci_high']:.2f}] | {t['p_corrected']:.3f} | {t['p_holm']:.3f} |")

    ra = V['rerun_agreement']
    out += ['', '## Table S16. Rerun agreement, model size and CPU latency', '',
            f"EfficientNet-B0 was retrained in the backbone experiment (same folds, seeds and schedule; `drop_last` in the training loader, as required by MobileNetV4). "
            f"Its mean macro F1 was {ra['novid']['here']:.2f} % (video frames excluded) against {ra['novid']['first']:.2f} % in the first experiment; "
            f"the mean absolute difference between matching runs was {ra['novid']['mean_abs_diff']:.2f} points (correlation {ra['novid']['corr']:.2f}). "
            f"On all test images the values were {ra['all']['here']:.2f} % and {ra['all']['first']:.2f} % (mean absolute difference {ra['all']['mean_abs_diff']:.2f} points).", '',
            '| Backbone | Parameters (M) | CPU latency, 1 thread, median (ms) | p90 (ms) | Mean training time per run (min) |', sep(24, 12, 20, 10, 16)]
    for c in BB:
        k = V['cost'][c]
        out.append(f"| {BL[c]} | {k['params_M']:.3f} | {k['cpu_ms_1thr_median']:.2f} | {k['cpu_ms_1thr_p90']:.2f} | {V['minutes_mean'][c]:.2f} |")
    out.append('')

    # S17 sensitivity to video-linked groups, S18 optimism of the validation images
    un = V.get('unsplit')
    if un:
        out += ['', '## Table S17. Sensitivity to the grouping of video frames: backbone comparison on test images whose video-linked group was not split', '',
                f"Mean test images per fold: {un['test_n_mean']:.1f}. Corrected resampled *t*-test over 20 folds; Holm adjustment over the four comparisons.", '',
                '| Backbone | Macro F1 (%), mean ± SD | Difference from EfficientNet-B0 (pp) [95% CI] | *p*, corrected | *p*, Holm | Folds higher |', sep(26, 18, 28, 10, 10, 10)]
        for c in BB:
            sm_ = un['summary'][c]
            if c == 'effb0':
                out.append(f"| {BL[c]} | {sm_['mean']:.2f} ± {sm_['sd']:.2f} | – | – | – | – |")
            else:
                p = un['paired'][c]
                out.append(f"| {BL[c]} | {sm_['mean']:.2f} ± {sm_['sd']:.2f} | {p['mean']:+.2f} [{p['ci_low']:.2f}, {p['ci_high']:.2f}] | {p['p_corrected']:.3f} | {p['p_holm']:.3f} | {p['wins']}/20 |")
    out += ['', '## Table S18. Optimism of the inner-validation images used for the referral threshold (video frames excluded)', '',
            'Mean accuracy without any referral on the validation images and on the test folds (means of per-run values), and the number of runs (of 40) in which the validation accuracy was already at or above the target.', '',
            '| Backbone | Validation accuracy (%) | Test accuracy (%) | Runs with validation accuracy ≥ 90 % | Runs with validation accuracy ≥ 95 % |', sep(26, 16, 14, 18, 18)]
    for c in BB:
        x9, x95 = V['novid']['selective']['90'][c], V['novid']['selective']['95'][c]
        out.append(f"| {BL[c]} | {x9['val_acc_mean']:.1f} | {x9['test_acc_mean']:.1f} | {x9['runs_val_meets_target']} | {x95['runs_val_meets_target']} |")
    out.append('')

    text = re.sub(r'(?<=[\s\[(,|])-(?=\d)', '−', '\n'.join(out))
    md = HERE / f'{STEM}.md'
    md.write_text(text)
    print('wrote', md)
    if shutil.which('pandoc'):
        subprocess.run(['pandoc', str(md), '-o', str(HERE / f'{STEM}.docx'), '--resource-path', str(HERE)], check=True)
        print('wrote', HERE / f'{STEM}.docx')
        pdf = subprocess.run(['pandoc', str(md), '-o', str(HERE / f'{STEM}.pdf'), '--resource-path', str(HERE),
                              '--pdf-engine=xelatex', '-V', 'geometry:a4paper,landscape,margin=1.6cm', '-V', 'mainfont=DejaVu Serif', '-V', 'fontsize=8pt'])
        if pdf.returncode != 0 and shutil.which('xelatex'):
            # fallback for TeX installations without lmodern: build the LaTeX source and drop that package
            tex = HERE / f'{STEM}.tex'
            subprocess.run(['pandoc', str(md), '-s', '-o', str(tex), '-V', 'geometry:a4paper,landscape,margin=1.6cm', '-V', 'mainfont=DejaVu Serif', '-V', 'fontsize=8pt'], check=True)
            tex.write_text(tex.read_text().replace('\\usepackage{lmodern}', ''))
            for _ in range(2):
                pdf = subprocess.run(['xelatex', '-interaction=nonstopmode', tex.name], cwd=HERE, capture_output=True)
            for ext in ['.tex', '.aux', '.log', '.out']:
                (HERE / f'{STEM}{ext}').unlink(missing_ok=True)
        ok = (HERE / f'{STEM}.pdf').exists()
        print('wrote', HERE / f'{STEM}.pdf' if ok else 'no PDF (LaTeX engine or fonts missing); use the .docx')


if __name__ == '__main__':
    main()
